# If true the exploit will be run every tick
enabled = true

# Teams that will be ignored when running this exploit
ignore_teams = []

# Exploit timeout in seconds. It will be killed after this time passes
# and you will be notified
timeout = 60

# List of discord handles (e.g "elnardu#1337") that will be notified in case
# this exploit fails
notifications = []

# Any additional metadata that you would like to provide
# to your exploit. Can be overridden when exploit is run manually
[meta]
hello = "world"
